language: python

services:
  - docker

before_install:
  - docker build -t lexrankr -f Dockerfile .

script:
  - docker run -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" lexrankr bash -c 'nosetests --config=.noserc && coveralls'
